name: Run pyright

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Installing python dependency
        run: pip install -r requirements.dev.txt
      - uses: jakebailey/pyright-action@v2
